apiVersion: v1
kind: Service
metadata:
  name: go-lgtmp
  labels:
    app: go-lgtmp
spec:
  type: ClusterIP
  selector:
    app: go-lgtmp
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
